export const ORDER_ADD_ITEM = 'ORDER_ADD_ITEM'
export const ORDER_REMOVE_ITEM = 'ORDER_REMOVE_ITEM'
export const ORDER_RESET = 'ORDER_RESET'

// export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
// export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
// export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'