export const WORKORDER_LIST_REQUEST = 'WORKORDER_LIST_REQUEST'
export const WORKORDER_LIST_SUCCESS = 'WORKORDER_LIST_SUCCESS'
export const WORKORDER_LIST_FAIL = 'WORKORDER_LIST_FAIL'

export const WORKORDER_DETAILS_REQUEST = 'WORKORDER_DETAILS_REQUEST'
export const WORKORDER_DETAILS_SUCCESS = 'WORKORDER_DETAILS_SUCCESS'
export const WORKORDER_DETAILS_FAIL = 'WORKORDER_DETAILS_FAIL'
export const WORKORDER_DETAILS_RESET = 'WORKORDER_DETAILS_RESET'

export const WORKORDER_CREATE_REQUEST = 'WORKORDER_CREATE_REQUEST'
export const WORKORDER_CREATE_SUCCESS = 'WORKORDER_CREATE_SUCCESS'
export const WORKORDER_CREATE_FAIL = 'WORKORDER_CREATE_FAIL'
export const WORKORDER_CREATE_RESET = 'WORKORDER_CREATE_RESET'

export const WORKORDER_UPDATE_REQUEST = 'WORKORDER_UPDATE_REQUEST'
export const WORKORDER_UPDATE_SUCCESS = 'WORKORDER_UPDATE_SUCCESS'
export const WORKORDER_UPDATE_FAIL = 'WORKORDER_UPDATE_FAIL'
export const WORKORDER_UPDATE_RESET = 'WORKORDER_UPDATE_RESET'