export const WORKORDER_LIST_REQUEST = 'WORKORDER_LIST_REQUEST'
export const WORKORDER_LIST_SUCCESS = 'WORKORDER_LIST_SUCCESS'
export const WORKORDER_LIST_FAIL = 'WORKORDER_LIST_FAIL'

export const WORKORDER_DETAILS_REQUEST = 'WORKORDER_DETAILS_REQUEST'
export const WORKORDER_DETAILS_SUCCESS = 'WORKORDER_DETAILS_SUCCESS'
export const WORKORDER_DETAILS_FAIL = 'WORKORDER_DETAILS_FAIL'
export const WORKORDER_DETAILS_RESET = 'WORKORDER_DETAILS_RESET'